apiVersion: v1
kind: Service
metadata:
  name: lumen-gateway
  namespace: default
  labels:
    app: lumen-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
    - port: 20880
      name: dubbo
  selector:
    app: lumen-gateway
