apiVersion: v1
kind: ConfigMap
metadata:
  name: lumen-auth
  namespace: default
data:
  DEPLOYMENT_ENV: test #定义环境配置
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: lumen-auth #名称
  labels:
    app: lumen-service #标注
spec:
  strategy:
    type: Recreate
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: lumen-auth
  template:
    metadata:
      labels:
        app: lumen-auth
    spec:
      containers: #docker容器的配置
        - name: lumen-auth
          image: zikesw-docker.pkg.coding.net/lumen/lumen-docker/lumen-auth:latest # pull镜像的地址
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 8080 #容器对外开放端口
          command: ["/bin/sh"]
          args: ["-c", "set -e && java -jar app.jar --spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
          env:
            - name: DEPLOYMENT_ENV_KEY
              valueFrom:
                configMapKeyRef:
                  name: lumen-auth #configmap名称
                  key: DEPLOYMENT_ENV
