apiVersion: v1
kind: Service
metadata:
  name: lumen-auth
  namespace: default
  labels:
    app: lumen-auth
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: lumen-auth
